### PR TITLE
Feature/simulations

### PR DESCRIPTION
**Pull request by aguumg**
* plots added
* intervals previous and old added to google sheet
* intervals written in google sheet using its names (and not as objects)
* defininf initial values in a date range where several actions has to be taken

### CODE REVIEW

**Review by Prithviraj8 — DISMISSED** [review]

**Comment by aguumg** [comment]
* fixed late execution of actions (we were updating interval_old after executing actions, it had to be updated before)
* added price_to_repay_aave once we open the short position (i.e. open_short updated)
* added collateral expressed in eth units and usd for aave
* parameters are updated for every new price now (before they were updated only after executing actions)

**Comment by aguumg** [comment]
* Gas fees added. We take them as a random number between 1usd and 9usd
* Funding rates added. We take them as a random number between -0.004% and 0.004%
* Withdrawal fees added as 0.01%
* Fees in aave added. We take them as: r_L a random number between 0.5% and 1.5%, r_b a random number between 1.5% and 2.5%

**Comment by aguumg** [comment]
* calculation of costs fixes. Now we calculate only when we execute actions
* added maker/taker fees taking a random number between 0.01% and 0.035%
* added aave attributes to track: lending fees, borrowing fees, interest earned by lending and borrowing and the difference between these two interests
   * total fees earned can be tracked now by reading interest_on_lending and/or lend_minus_borrow_fees
* update_parameter method updated in order to add lending fees into the collateral value in aave and borrowing fees into the debt in aave
   *  this change also involved adding two extra attributes for initial_collateral and initial_debt in order to use them when we open the short position and when we add collateral in dydx, respectively
* we separete 10% of the initial collatearl as a reserve margin
* we updated the write_data method in order to limit the number of attributes written in the sheet

**Comment by aguumg** [comment]
* Volatility_calculator added (has to be finished)
* Started simulations taking daily and weekly std as vol
* initialize_volatility_calc, define_target_prices, define_intervals modules added
   * all intervals havea threshold of 1+vol except borrow_usdc, return_usdc, remove_coll_dydx that have 1+2*vol; and add_coll_dydx that has 1+3*vol (it takes 1 minute)
* put_limit_order taken equal to close_short
* close_short method calls cancel_order 
   * cancel_order adder (has to be finished)
* added an alert in open_short, close_short methods if we open at a lower price than floor and if we close at a higher price than close_short price

**Comment by aguumg** [comment]
* simpler algo
	- added parameter_manager to define/update parameters and execute actions
	- added data_dumper to write and plot data
* data dumper also writes csv (faster than writting google sheets)
	- added header
	- added data
	- round fees 
	- delete files
* trigger prices and intervals reduced: In order to make the strategy simplet we will try using 5 triggering points: return_usdc_and_remove_coll_dydx, borrow_usdc, add_coll_dydx, close_short and open_short
* we are using std from exponential moving average as volatility metric
* updated the way we execute actions: we were executing always actions regarding the name of the interval which is the name of the right border price. That implied executing always right border actionn (which are actions needed for increasing prices) and never left border actions (which are actions needed for decreasing prices)

**Pull request merged**
